// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfALI8IJr5apwI7eLFGT2FRAe4RSzXC1U',
    appId: '1:135398213806:web:a0b485fc50699a7ade053f',
    messagingSenderId: '135398213806',
    projectId: 'notesapp-11f88',
    authDomain: 'notesapp-11f88.firebaseapp.com',
    storageBucket: 'notesapp-11f88.appspot.com',
    measurementId: 'G-QTWG6ZL1Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Mk4n8LQ5x4-4N2V3jIhs_IBtKcP9WPI',
    appId: '1:135398213806:android:4cc2d315b5104fc7de053f',
    messagingSenderId: '135398213806',
    projectId: 'notesapp-11f88',
    storageBucket: 'notesapp-11f88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XtgsjcFEMnM_Y0YQtj1n25p-CsuyuOE',
    appId: '1:135398213806:ios:062e3b2539cf756ade053f',
    messagingSenderId: '135398213806',
    projectId: 'notesapp-11f88',
    storageBucket: 'notesapp-11f88.appspot.com',
    iosBundleId: 'com.kristel.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1XtgsjcFEMnM_Y0YQtj1n25p-CsuyuOE',
    appId: '1:135398213806:ios:f04034d44e77d52dde053f',
    messagingSenderId: '135398213806',
    projectId: 'notesapp-11f88',
    storageBucket: 'notesapp-11f88.appspot.com',
    iosBundleId: 'com.kristel.notesapp.RunnerTests',
  );
}
